import pandas as pd
import time
import warnings
from datetime import datetime
import logging

logger = logging.getLogger(__name__)
warnings.filterwarnings("ignore")

COLS_TO_SUM = ["sentiment", "duration", "number_words", "number_chars", "number_lines"]
COLS_TO_DROP = ["read_date", "read_time", "accept_date", "accept_time", "delay"]


"""
A SHORT READ ME BEFORE RUNNING THIS CODE:

1. The files that need to be inputed to this run are: exploded and df_1_not_merged_2_merged_04_1_26.
2. I recommand putting the files in the directory (the pwd that you are working on - git hub folder) with the names founded in the read.csv
3. This code runs with a logger, meaning that logs will not appear in the terminal, but will create a text files with all logs.
4. That way we can look excactly what happend for each run in the code. 
5. IMPORTANT - verify the df_1_not_merged_2_merged.csv (or after stage 1 df) is ordered by the following logic:

id_session desc/asc
end_time ordered asc
event_type desc

"""

def main(merged_df: pd.DataFrame, df_exploded: pd.DataFrame, today_str: str):
    logging.basicConfig(level=logging.INFO, filename=f"big_code_{today_str}.txt")
    # Start timing
    start_time = time.time()
    # STEP 1: Preprocess merged_df
    # Make sure to strip column names (remove extra spaces)
    merged_df.columns = merged_df.columns.str.strip()
    df_exploded.columns = df_exploded.columns.str.strip()
    # Sort for efficient filtering
    merged_df = merged_df.sort_values(["id_session", "end_time", 'event_type'], ascending= [True, True, False])

    # Group by session for fast access
    logger.info(
        "Creating a tuple grouped by object of sessions in merged df for faster processing..."
    )
    session_groups = dict(tuple(merged_df.groupby("id_session")))

    # List to collect results
    filtered_events_list = []

    # STEP 2: Iterate over df_exploded
    total_alternatives = len(df_exploded)
    print(f"Stage 3: processing {total_alternatives:,} alternatives...", flush=True)
    for i, row in enumerate(df_exploded.reset_index().itertuples(index=False)):
        if i % 100000 == 0:
            print(
                f"Stage 3: {i:,}/{total_alternatives:,} alternatives "
                f"({100 * i / max(total_alternatives, 1):.0f}%), "
                f"{len(filtered_events_list):,} rows kept",
                flush=True,
            )
        logger.info(f"Working on concurrent session: {row.concurrent_sessions}")
        session_events = session_groups.get(row.concurrent_sessions, pd.DataFrame())
        logger.info(f"Found {len(session_events)} events of that session in merged_df")

        if session_events.empty:
            logger.info(f"session has no rows in merged_df, continue!")
            logger.info("--------------------------------------")
            continue

        # Get only events before the choice time
        past_events = session_events[session_events["end_time"] < row.time]

        if past_events.empty:
            logger.info(
                f"session has no rows earlier than the chosen time in merged_df, continue!"
            )
            logger.info("--------------------------------------")
            continue

        # Collect all consecutive type=1 messages since the last agent reply.
        # Pending = type=1 with end_time >= last reply (NOT strict >): end_time is whole-second,
        # so a visitor message can share the exact second of the agent's last reply. Stage 1's
        # canonical sort (id_session, end_time asc, event_type desc) places such a type=1 AFTER
        # the type=2 at that second, i.e. treats it as pending. A strict > drops it and yields a
        # spurious empty turn (this is what made choice_set 3996 a no-chosen set). NOTE: the
        # agent-first tie-break is itself chronologically backwards ~60% of the time — a known
        # limitation (CLAUDE.md Known Issues #7, "Problem 2"), deferred.
        past_type2 = past_events[past_events["event_type"] == 2]

        if past_type2.empty:
            consecutive_type1 = past_events[past_events["event_type"] == 1]
        else:
            last_agent_reply_time = past_type2["end_time"].max()
            consecutive_type1 = past_events[
                (past_events["event_type"] == 1) &
                (past_events["end_time"] >= last_agent_reply_time)
            ]

        # choice_time is the reference used for waiting_time; normally the choice moment.
        choice_time = row.time

        if consecutive_type1.empty:
            # Option 3: a flag=1 choice set is generated by a re-engagement reply
            # (agent replied again to a session whose visitor said nothing new), so the
            # chosen session has no pending turn. Instead of dropping it (which would make
            # a no-chosen choice set), reuse the visitor turn from this session's genuine
            # reply, reconstructed straight from the timeline (this also auto-handles
            # chained flag=1 events, since they all point at the same most-recent turn).
            row_flag = getattr(row, "flag", 0)
            type1_past = past_events[past_events["event_type"] == 1]
            if row_flag == 1 and row.chosen == 1 and not type1_past.empty:
                last_type1_time = type1_past["end_time"].max()
                type2_after = past_type2[past_type2["end_time"] > last_type1_time]
                type2_before = past_type2[past_type2["end_time"] < last_type1_time]
                if type2_after.empty:
                    logger.info("flag=1 chosen but no genuine reply found, skipping.")
                    logger.info("--------------------------------------")
                    continue
                genuine_reply_time = type2_after["end_time"].min()
                turn_lower_bound = type2_before["end_time"].max() if not type2_before.empty else float("-inf")
                # >= turn_lower_bound (same same-second tie reasoning as the main path):
                # the first message of the reconstructed turn may share the second of the
                # preceding reply and must still be included.
                consecutive_type1 = past_events[
                    (past_events["event_type"] == 1) &
                    (past_events["end_time"] >= turn_lower_bound) &
                    (past_events["end_time"] <= last_type1_time)
                ]
                # waiting_time uses the genuine reply (response latency of the turn), per option 3.
                choice_time = genuine_reply_time
                logger.info(
                    f"flag=1 re-engagement: reused genuine turn, waiting_time to {genuine_reply_time}"
                )
            else:
                logger.info("No pending visitor messages since last agent reply, skipping.")
                logger.info("--------------------------------------")
                continue

        consecutive_type1 = consecutive_type1.sort_values("end_time").reset_index(drop=True)
        aggregated_row = consecutive_type1.iloc[[0]].copy()
        for col in COLS_TO_SUM:
            if col in aggregated_row.columns:
                aggregated_row[col] = consecutive_type1[col].sum()
        aggregated_row["n_messages"] = len(consecutive_type1)
        cols_to_drop_present = [c for c in COLS_TO_DROP if c in aggregated_row.columns]
        aggregated_row = aggregated_row.drop(columns=cols_to_drop_present)

        first_end_time = aggregated_row["end_time"].iloc[0]
        aggregated_row = aggregated_row.assign(
            choice_set=row.index,
            chosen=row.chosen,
            waiting_time=choice_time - first_end_time,
            chosen_time=choice_time,
            workload=row.workload,
            flag=getattr(row, "flag", 0),
        )

        filtered_events_list.append(aggregated_row)
        logger.info(
            f"Enriched filtered events list by 1 row: {row.concurrent_sessions}, {row.chosen}, "
            f"n_messages={aggregated_row['n_messages'].iloc[0]}, waiting_time={choice_time - first_end_time}"
        )

        logger.info("--------------------------------------")

    # STEP 3: Combine and save
    if filtered_events_list:
        all_filtered_events = pd.concat(filtered_events_list, ignore_index=True)
        out_name = f"df_choicesets_{today_str}.csv"
        all_filtered_events.to_csv(out_name, index=False)
        print(f"Stage 3: wrote {out_name} ({len(all_filtered_events):,} rows)", flush=True)
    else:
        logger.info("No filtered events found.")
        print("Stage 3: no filtered events found — nothing written.", flush=True)

    # STEP 4: Execution time
    end_time = time.time()
    print(f"Stage 3: done in {(time.time() - start_time) / 60:.1f} min", flush=True)
    logger.info(f"Execution time: {end_time - start_time:.2f} seconds")


if __name__ == "__main__":
    import sys

    merged_path = sys.argv[1] if len(sys.argv) > 1 else "df_1_not_merged_2_merged.csv"
    exploded_path = sys.argv[2] if len(sys.argv) > 2 else "df_exploded_all_data.csv"
    today_str = datetime.today().strftime("%d_%m_%Y")

    merged_df = pd.read_csv(merged_path)
    df_exploded = pd.read_csv(exploded_path)
    main(merged_df, df_exploded, today_str)
